### ISSUE TITLE
Feature: Allow initialization via constructor arguments.

### ISSUE THREAD

**Issue by clarketm** [eyas-ranjous/datastructures-js#26]
@eyas-ranjous – I want to start by thanking you for this library; for classical, mutable ADTs it is compendious. These abstract data types are an essential addition to the JavaScript language that I know we all wish were part of the language. I wanted to ask you if allowing for initialization values via the constructor is something you would be willing to add (or allow via PR), for the _collection_ types (e.g. `Stack`, `Queue`, `Set`, etc.). Signatures similar to those of [Immutable.js](https://facebook.github.io/immutable-js/docs/#/Stack/Stack) is what I had in mind. 

> The example below is for a `stack` but would apply to other applicable collection types 

*e.g.*
```js
// Stack<T>(): Stack<T>
let s1 = ds.stack(); 
// s1._elements === []

// Stack<T>(collection: Iterable<T>): Stack<T>
let s2 = ds.stack([1, 2, 3]); 
// s2._elements === [1, 2, 3]
```

**Comment by eyas-ranjous** [comment]
@clarketm I appreciate your feedback and thanks for the suggestion 👍yes it makes sense to enable initializing the structures from constructor, I built them without taking that in consideration, please feel free to submit a PR and assign it to me for review. Cheers!

**Comment by clarketm** [comment]
@eyas-ranjous – Sorry, I haven't had the time recently to work on this, but I still have this feature request planned. I can revisit this in the coming weeks at which time we can reopen if this is still something of interest.

**Comment by eyas-ranjous** [comment]
no worries. please feel free to re-open it and add the feature. cheers!
