### ISSUE TITLE
hashtable error on remove inside collision

### ISSUE THREAD

**Issue by yiwensong** [eyas-ranjous/datastructures-js#3]
I'm getting an error on the following code:

``` javascript
var ds = require("datastructures-js");
var d = ds.hashtable();
var N = 100000;
for (var i=0;i<N;i++) d.put(i,i);
for (var i=0;i<N;i++) d.remove(i);
```

This seems to only happen when `N` is large. It seems like the issue is in the array splicing during removal. (The iterating index runs off of the array after you splice. -- Line 79-84 in lib/dataStructures/hashtable.js)

The error I get is:

```
TypeError: Cannot read property 'getKey' of undefined
at self.remove in datastructures-js/lib/dataStructures/hashtable.js — line 80
```

**Comment by eyas-ranjous** [comment]
Hi @yiwensong. indeed, the issue is caused by using a pre assigned `length` variable while changing the array length inside the for loop and without decreasing the `i`. thanks for reporting the bug. I will fix it asap.

**Comment by eyas-ranjous** [comment]
Fix is released. v3.0.7
